---
#------------------------------------------------------------------------------
# Main YAML Playbook to launch ISE with Meraki vMX in AWS
#------------------------------------------------------------------------------


- name: AWS VPC with Cisco ISE and Meraki vMX 
  hosts: localhost
  gather_facts: yes   # required for `ansible_date_time`
  vars_files:
    vars/main.yaml
  tasks:


  - name: Create SSH KeyPair
    ansible.builtin.include_tasks: ssh_key_pair.yaml


  - name: Create VPC
    ansible.builtin.include_tasks: ise_in_aws.vpc.yaml


  - name: Create ISE (no wait)
    ansible.builtin.include_tasks: ise_in_aws.ise.yaml


  - name: Create vMX
    ansible.builtin.include_tasks: ise_in_aws.vmx.yaml
    tags: meraki,vmx


  - name: Create PingVM
    ansible.builtin.include_tasks: ise_in_aws.ping_vm.yaml


  - name: Wait for ISE to be Initialized
    loop: "{{ ise_nodes }}"
    ansible.builtin.include_tasks: tasks/ise_initialized.yaml


...
