---
#------------------------------------------------------------------------------
# Main YAML Playbook to launch ISE with Meraki vMX in AWS
#------------------------------------------------------------------------------


- name: Provision AWS VPC with Cisco ISE and Meraki vMX 
  hosts: localhost
  gather_facts: no
  vars_files:
    vars/main.yaml
  tasks:

  - name: Create SSH KeyPair
    ansible.builtin.include_tasks: ssh_key_pair.yaml

  - name: Create VPC
    ansible.builtin.include_tasks: ise_in_aws.vpc.yaml

  - name: Create ISE (no wait)
    ansible.builtin.include_tasks: ise_in_aws.ise.yaml

  - name: Create vMX
    ansible.builtin.include_tasks: ise_in_aws.vmx.yaml
    tags: meraki,vmx

  - name: Create PingVM
    ansible.builtin.include_tasks: ise_in_aws.ping_vm.yaml

  - name: Create Meraki MR SSIDs
    ansible.builtin.include_tasks: ise_in_aws.mr_ssids.yaml

  - name: Refresh AWS Inventory to get the new Instance(s)
    ansible.builtin.meta: refresh_inventory


- name: Initialize ISE Node(s)
  hosts: ise
  gather_facts: no
  vars_files:
    vars/main.yaml
  tasks:

  - name: Wait for ISE Application Server Initialization
    ansible.builtin.include_tasks: tasks/ise_initialized.yaml

  - name: Show ISE Node Login URLs
    loop: "{{ ise_nodes }}"
    ansible.builtin.debug:
      msg: |
         
                .
               /|\
              /|||\
           @ /|||||\ @
          @  \|/ \|/  @   https://{{ ansible_host }}
          @           @   https://{{ inventory_hostname }}.{{ domain_name }}
           @.       .@
            `Y@ @ @Y`
         
         


  # - name: Press Enter to Continue
  #   ansible.builtin.pause:
  #     prompt: |
  #        
  #         █  █    
  #         █  █    Press Enter to Continue and Configure ISE!
  #         █  █    
  #        


  - name: Configure ISE
    ansible.builtin.include_tasks: ise.configuration.yaml


  - name: ISE ({{ inventory_hostname }}) is Ready!
    ansible.builtin.pause:
      seconds: 1
      prompt: |
         
         
                .
               /|\
           @  /|||\  @      ___                _        _
          @  /|||||\  @    | _ \ ___  __ _  __| | _  _ | |
          @  \|/ \|/  @    |   // -_)/ _` |/ _` || || ||_|
           @.       .@     |_|_\\___|\__,_|\__,_| \_, |(_)
            `Y@ @ @Y`                             |__/
         
         


...
