---
#------------------------------------------------------------------------------
# Main YAML Playbook to launch ISE with Meraki vMX in AWS
#------------------------------------------------------------------------------


- name: vMX settings
  hosts: localhost
  gather_facts: yes   # required for `ansible_date_time`
  vars_files:
    vars/main.yaml
  tasks:



  - name: Find {{ meraki_vpn_hub.net_name }} Network to use as VPN Hub
    cisco.meraki.meraki_network:
      org_name: "{{ meraki_org_name }}"
      net_name: "{{ meraki_vpn_hub.net_name }}"
      state: query
    register: lab_network

  - name: Show lab_network
    ansible.builtin.debug: var=lab_network




  - name: Set vMX to VPN Spoke mode to Lab Hub
    cisco.meraki.meraki_site_to_site_vpn:
      org_name: "{{ meraki_org_name }}"
      net_name: "{{ meraki_net_name }}"
      state: present
      mode: spoke     # use `spoke` to avoid AWS $$$ for `hub` traffic
      hubs:
      - hub_id: "{{ lab_network.data.id }}"
        use_default_route: false  # send all default route traffic to this hub

      # 🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞
      #
      # Cannot Add Local Network via API! 8-(  
      #
      # Unrecognized subnet 172.31.0.0/16 for Passthrough MX - 
      # only Client VPN subnet(s) permitted
      # Status: 400
      # 
      # Must do it manually in Dashboard:
      #   Security & SDWAN > Configure > Site-to-Site VPN > Local Networks
      # 
      # subnets:
      # - local_subnet: 172.31.0.0/16
      #   use_vpn: true 
      #
      # 🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞  🐞

    register: spoke_mode

  - name: spoke_mode
    ansible.builtin.debug: var=spoke_mode


...
