---

# -----------------------------------------------------------------------------
# Verify your inventory:
#   ansible-inventory --graph
#   ansible-inventory --list
#
# There are two default groups:
#   - all : contains every host
#   - ungrouped : contains all hosts not belonging to another group
#
# You may create groups based on
#   - What : an application, stack or microservice
#   - Where : a datacenter, region, local, storage, etc.
#   - When : the development stage for prod, test, etc.
#
# For details on creating Ansible inventory files, see
#   https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
# For common patterns for targeting inventory hosts and groups:
#   https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
# -----------------------------------------------------------------------------

all:
  #
  # Ungrouped Hosts - names should be DNS-compatible
  #
  hosts:
    localhost:
      ansible_connection: local   # deploy playbook to control machine
      ansible_host: 127.0.0.1
    ise:

  # global vars
  vars:



