---

#
# Create Endpoint Task
#

# - name: Default endpoint group ID
#   ansible.builtin.set_fact: 
#     default_endpoint_group: aa13bb40-8bff-11e6-996c-525400b48521

- name: Create Endpoint
  when: endpoints is defined and endpoints | length > 0
  vars:
    default_endpoint_group: aa13bb40-8bff-11e6-996c-525400b48521
  loop: "{{ endpoints }}"
  cisco.ise.endpoint:
    ise_hostname: "{{ inventory_hostname }}"
    ise_username: "{{ ise_username }}"
    ise_password: "{{ ise_password }}"
    ise_verify: "{{ ise_verify }}"
    state: present
    mac: "{{ item.mac }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    staticGroupAssignment: "{{ item.staticGroupAssignment | default(true) }}"
    groupId: "{{ item.groupId | default( default_endpoint_group ) }}"
    # ▼▼▼ optional attributes ▼▼▼
    # staticProfileAssignment:  "{{ staticProfileAssignment | default(false) }}"
    # profileId: "{{ groupId | default('0a9c6890-8c00-11e6-996c-525400b48521') }}"
    # customAttributes:
    #   customAttributes:
    #     Created: "{{ created | default(now()) }}"
    #     Expired: 
  tags: 
  - create
  - endpoint


...
