---
#
# Tasks for creating cisco.ise.internal_user from a list: `internal_users`
#

  - name: Create Internal User Accounts 
    when: internal_users is defined and internal_users | length > 0
    loop: "{{ internal_users }}"
    vars:
      default_identity_groups: a1740510-8c01-11e6-996c-525400b48521  # Employee
    cisco.ise.internal_user:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: "{{ item.state | default('present') }}"
      name: "{{ item.username }}"
      password: "{{ item.password | default('C1sco12345') }}"
      changePassword: "{{ item.changePassword | default(false) }}"
      enabled: "{{ item.enabled | default(true) }}"
      expiryDateEnabled: "{{ item.expiryDateEnabled | default(false) }}"
      passwordIDStore: Internal Users
      identityGroups: "{{ item.identityGroups | default(default_identity_groups) }}"
    register: create_users
    tags: 
    - internal_user
    - create

  # - name: create_users
  #   ansible.builtin.debug: var=create_users
  #   tags: internal_user


  #----------------------------------------------------------------------------
  # cisco.ise.internal_user Template
  #----------------------------------------------------------------------------
  # - name: internal_user 
  #   cisco.ise.internal_user:
  #     ise_hostname: "{{ inventory_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     state: present
  #     name: '{{ item.name }}'
  #     description: '{{ item.description | default() }}'
  #     enabled: '{{ item.enabled | default(true) }}'
  #     password: '{{ item.password | default(default_password) }}'
  #     # ▼▼▼ optional attributes ▼▼▼
  #     # changePassword: '{{ item.changePassword | default(false) }}'
  #     # passwordIDStore: '{{ item.idStore | default(Internal Users) }}'
  #     # identityGroups: a1740510-8c01-11e6-996c-525400b48521
  #     # customAttributes:
  #     #   Created: 
  #     #   Expired: 
  #   register: results


...
