---
#
# Test for ISE Application Server Initialization
#

  - name: Ping {{ item.private_ip }}
    ansible.builtin.ping:
    register: result
    until: result.failed == false
    retries: 100
    delay: 5


  - name: Wait for {{ item.private_ip }} App Server (GUI)
    ansible.builtin.uri:
      url: https://{{ item.private_ip }}/admin/login.jsp
      method: GET
      follow_redirects: safe
      timeout: 10
      validate_certs: no
      return_content: no
    register: result
    until: result.status == 200
    retries: 1000
    delay: 10

  - name: Show {{ item.private_ip }} Initialized
    when: result.status == 200
    ansible.builtin.debug: 
      msg : "✅ ISE Application Server {{ item.private_ip }} Initialized"


...
