---
#
# Test for ISE Application Server Initialization
#

  - name: Ping {{ pingvm_private_ip }}
    delegate_to: localhost
    ansible.builtin.ping:
    register: result
    until: result.failed == false
    retries: 100
    delay: 5


  - name: Wait for ISE App Server (GUI) | {{ inventory_hostname }}
    delegate_to: localhost
    ansible.builtin.uri:
      url: https://{{ ansible_host }}/admin/login.jsp
      method: GET
      follow_redirects: safe
      timeout: 10
      validate_certs: no
      return_content: no
    register: result
    until: result.status == 200
    retries: 1000
    delay: 10

  - name: Initialized? | {{ inventory_hostname }}
    when: result.status == 200
    ansible.builtin.debug:
      msg : "✅ ISE Application Server {{ item.private_ip }} Initialized"


...
